apiVersion: v1
kind: ConfigMap
metadata:
  name: pookie-api-config
data:
  RabbitMQ__HostName: "rabbitmq"
  RabbitMQ__VirtualHost: "/"
  ObservabilityOptions__CollectorUrl: "http://otel-collector:4317"