receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  jaeger:
    endpoint: "jaeger:14250"  # Ensure this matches the Jaeger service name and port
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: ["health_check"]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
