apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0bXEtbXVzZXI=  # base64 encoded rabbitmq-user
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=  # base64 encoded password
